// <auto-generated />
namespace Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_name_parkingtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_name_parkingtime));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231043009_change_name_parkingtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
