// <auto-generated />
namespace Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_last_name_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_last_name_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201711070824037_first_last_name_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
